name: GitHub Action

on: [push]

env:
  DOTNET_NOLOGO: true
  NBGV_VERSION: 3.1.91  
  GprToolCsprojPath: src/GprTool/GprTool.csproj
  config: Release
  branch: action

jobs:

  build-and-test:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - uses: dotnet/nbgv@v0.3.1
      with:
        setAllVars: true

    - name: Setup dotnet using global.json
      uses: actions/setup-dotnet@v1.5.0

    - run: dotnet publish $GprToolCsprojPath -c ${{ env.config }}

    - name: Publish GitHub Action
      run: |
        git checkout -b ${{ env.branch }}
        git config --global user.name "Jamie Cansdale"
        git config --global user.email "jcansdale@gmail.com"
        git add -f src/GprTool/bin/${{ env.config }}/netcoreapp3.0/publish
        git commit -m "Add published files"
        git push --set-upstream origin ${{ env.branch }} --force
        git tag $TAG_NAME
        git push origin $TAG_NAME
      env:
        TAG_NAME: v${{ env.NBGV_SemVer2 }}
